from django.db import models


class HRTEMP(models.Model):

    HRTEMPID = models.IntegerField(primary_key=True)
    STATUSCODE = models.CharField(max_length=1)
    SRCCNCID = models.IntegerField()
    COMPANYNO = models.DecimalField(max_digits=2, decimal_places=0)
    DIVISIONNO = models.DecimalField(max_digits=3, decimal_places=0)
    CHGCNCID = models.IntegerField()
    CHGCOMPANY = models.IntegerField()
    CHGDIVISION = models.DecimalField(max_digits=3, decimal_places=0)
    EMPCNCID = models.IntegerField()
    EMPCOMPANY = models.DecimalField(max_digits=2, decimal_places=0)
    EMPDIVISION = models.DecimalField(max_digits=3, decimal_places=0)
    PRTMSTID = models.IntegerField()
    EMPLOYEENO = models.IntegerField()
    SOCIALSECNO = models.DecimalField(max_digits=9, decimal_places=0)
    EMPLNAME = models.CharField(max_length=30)
    ABBRV = models.CharField(max_length=10)
    ADDR1 = models.CharField(max_length=30)
    ADDR2 = models.CharField(max_length=30)
    ADDR3 = models.CharField(max_length=30)
    CITY = models.CharField(max_length=20)
    STATECODE = models.CharField(max_length=2)
    ZIPCODE = models.DecimalField(max_digits=3, decimal_places=0)
    COUNTRYCODE = models.DecimalField(max_digits=3, decimal_places=0)
    AREACODE = models.DecimalField(max_digits=3, decimal_places=0)
    PHONENO = models.DecimalField(max_digits=7, decimal_places=0)
    CELLPHAC = models.DecimalField(max_digits=3, decimal_places=0)
    CELLPHNO = models.DecimalField(max_digits=7, decimal_places=0)
    CONTACTNAME = models.CharField(max_length=30)
    CONTACTAC = models.DecimalField(max_digits=3, decimal_places=0)
    CONTACTPHONE = models.DecimalField(max_digits=7, decimal_places=0)
    BUSUFFIX = models.CharField(max_length=4)
    CNTRYCODE = models.CharField(max_length=3)
    MARITALSTAT = models.CharField(max_length=1)
    LVLCODE = models.DecimalField(max_digits=2, decimal_places=0)
    OFFICERSCODE = models.CharField(max_length=1)
    HRTOCCID = models.IntegerField()
    OCCUPDESC1 = models.CharField(max_length=20)
    OCCUPDESC2 = models.CharField(max_length=20)
    SEXCODE = models.CharField(max_length=1)
    MINORITYCODE = models.DecimalField(max_digits=1, decimal_places=0)
    HANDICAPCODE = models.CharField(max_length=1)
    DISABLEVEL = models.CharField(max_length=2)
    BLOODTYPE = models.CharField(max_length=3)
    BIRTHPLACE = models.CharField(max_length=25)
    PERMRESIDENT = models.CharField(max_length=1)
    DRIVERLICNO = models.CharField(max_length=25)
    DLNUMBER = models.CharField(max_length=8)
    BIRTHDATE = models.DateField()
    ORIGHIREDATE = models.DateField()
    ADJHIREDATE = models.DateField()
    VACELIGDATE = models.DateField()
    LASTYEDATE = models.DateField()
    ELIGSCKACCRL = models.DateField()
    SICKACRLDATE = models.DateField()
    EXPIREDATE = models.DateField()
    RETIREDDATE = models.DateField()
    VISAEXPDATE = models.DateField()
    REVIEWDATE = models.DateField()
    ESTAVAILDATE = models.DateField()
    ISSUEI9DATE = models.DateField()
    I9EXPDATE = models.DateField()
    ISSUEI9 = models.CharField(max_length=1)
    COBRALTRDATE = models.DateField()
    COBRALTRRCVD = models.DateField()
    COBREASNTFLG = models.CharField(max_length=1)
    REHIREDATE = models.DateField()
    HOLELIGDATE = models.DateField()
    DISABILITYDT = models.DateField()
    TERMDATE = models.DateField()
    PRTTRMID = models.IntegerField()
    TERMCODE = models.DecimalField(max_digits=2, decimal_places=0)
    LASTDAYWK = models.DateField()
    BENEFITGP = models.CharField(max_length=50)
    ISSUEAUTH = models.CharField(max_length=25)
    EVERIFYDT = models.DateField()
    EVERCASE = models.CharField(max_length=15)
    EVERCRES = models.CharField(max_length=25)
    TERMRSN = models.DecimalField(max_digits=3, decimal_places=0)
    ELGBRHIRE = models.CharField(max_length=1)
    PRTLBRID = models.IntegerField()
    DEPTNO = models.DecimalField(max_digits=3, decimal_places=0)
    PRTECLID = models.IntegerField()
    EMPLCLASS = models.DecimalField(max_digits=3, decimal_places=0)
    EMPLTYPE = models.CharField(max_length=2)

    def __str__(self):
        return f"{self.HRTEMPID}"

    class Meta:
        ordering = ['HRTEMPID']
